#!/data/data/com.termux/files/usr/bin/light-sudo bash
# This file is part of Light Kernel Manager.
#
# Lodacum Kernel Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Lodacum Kernel Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Lodacum Kernel Manager.  If not, see <https://www.gnu.org/licenses/>.
#
# Copyright (C) 2023-2024 revWhiteShadow

# Check dependencies
if ! hash fzf fzy jq curl sqlite3; then
	echo "[-] Environment has missing dependencies"
	exit 127
fi

[ ! -d /data/LKM-kernel ] && mkdir /data/LKM-kernel

# Dirty fix for check4update
root_gid_hack() {
	su -lp $SUDO_GID -c "$@"
}

if [ ! -f /data/data/com.termux/files/usr/share/LKM-kernel/init_run.sh ]; then
	echo "[-] Faulty installation detected !"
	echo "[*] Please reinstall LKM"
	exit 1
fi

source /data/data/com.termux/files/usr/share/LKM-kernel/init_run.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/menu_helper.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/database_util.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/settings.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/utils/cpu/cpu_util.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/utils/gpu/gpu_util.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/utils/dram/dram_util.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/utils/memory/memory_util.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/utils/net/net_util.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/utils/disp/disp_util.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/utils/misc/misc_util.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/utils/battery/battery_util.sh
source /data/data/com.termux/files/usr/share/LKM-kernel/utils/sched/sched_util.sh

LINE=$(stty size | awk '{print $2}')
TERMUX_PATH="/data/data/com.termux/files/usr/bin"
ANDROID=$(getprop ro.build.version.release)
ENTROPY="$(cat /proc/sys/kernel/random/entropy_avail)/$(cat /proc/sys/kernel/random/poolsize) ($(($(cat /proc/sys/kernel/random/entropy_avail) * 100 / $(cat /proc/sys/kernel/random/poolsize)))% available)"
VENDOR=$(getprop "ro.product.manufacturer")
VERSION="v1.1.5"

trap "tput cnorm" EXIT

if [ ! -f $database_path ]; then
	create_database
fi

if [[ $(get_db_version) != "$VERSION" ]]; then
	update_db_version
fi

if [ $(risk_acceptence) -eq 1 ] && [ ! -f /dev/lkm-execstoredcmd ] && [ $(sql_query "SELECT execstoredcmd FROM tb_info;") -eq 1 ]; then
	init_execstoredcmd
	touch /dev/lkm-execstoredcmd
fi

# User agreement
if [ $(risk_acceptence) -eq 0 ]; then
	clear
	echo -e "Light Yagami Kernel Manager ${VERSION}"
	echo -e "Copyright (c) 2023-2024 revWhiteShadow\n"
	echo -e "DISCLAIMER AND LICENSE AGREEMENT\n"
	echo -e "Lodacum Kernel Manager offers advanced root functions that could potentially harm your device if used incorrectly or in combination with other software, tweaks, or modules. Please be cautious as Lodacum Kernel Manager does not take responsibility for any damages resulting from the misuse of this software.\n\nIf you are not well-versed in how root access functions, it's advisable to refrain from utilizing the root options until you have a complete understanding of the associated risks.\n\nThis software is licensed under the GNU General Public License v3.0. It comes with NO WARRANTY AND LIABILITY. By using this software, you acknowledge and accept full responsibility for its use. You agree that any actions taken with this software that negatively impact your device are not the responsibility of the developer.\n\n" | fold -s -w ${LINE}
	read -p "Type 'I AGREE' to continue: " a1
	case $a1 in
	"I AGREE") accept_risk ;;
	*)
		clear
		echo -e "\033[38;5;196m[-] Not agreed, Aborted.\033[0m"
		exit 0
		;;
	esac
fi

show_license() {
	clear
	echo -e "Lodacum Kernel Manager ${VERSION}
Copyright (c) 2023-2024 revWhiteShadow

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 3. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program; if not, Kindly write a message to me revWhiteShadow.

Report problems and questions to https://t.me/godTspeed or https://github.com/white9shadow/light_kernel_manager

revWhiteShadow <White9Shadow>


[*] Press enter to back into main menu
" | fold -s -w ${LINE}
	read -r -s
}

donate() {
	nohup /system/bin/am start -a android.intent.action.VIEW -d https://www.ko-fi/revws </dev/null >/dev/null 2>&1 &
}


check4update() {
	echo -e "\n[*] Checking for new update..."

	if [[ $(root_gid_hack $TERMUX_PATH/apt list) == *LKM-kernel* ]]; then
		install_deb=1
	fi >/dev/null 2>&1

	repo_info=$(curl -s "https://api.github.com/repos/rem01gaming/light_kernel_manager/releases/latest")
	if [[ $? != 0 ]]; then
		echo "[-] Can't fetch repository info from GitHub API, make sure you're online."
		echo "[*] Press enter to back into main menu"
		read -r -s
		return 0
	fi

	latest_release=$(echo $repo_info | jq -r ".tag_name")

	if [[ "$VERSION" == "$latest_release" ]]; then
		echo "[+] Current version is Up-to-date :)"
		echo "[*] Press enter to back into main menu"
		read -r -s
		return 0
	else
		read -p "New version is found, update now? [Y/n] " confirm_update

		case $confirm_update in
		y | Y) ;;
		*) return 0 ;;
		esac
	fi

	if [ ! -z $install_deb ]; then
		echo "[*] downloading update files..."
		rm -f ~/LKM-kernel.deb
		curl -o ~/LKM-kernel.deb -L https://github.com/revWhiteShadow/light_kernel_manager/releases/download/$latest_release/LKM-kernel.deb >/dev/null 2>&1
		echo "[*] Installing update..."
		[ ! -f ~/LKM-kernel.deb ] && echo "[-] Error while downloading update file" && exit 1
		root_gid_hack $TERMUX_PATH/apt remove LKM-kernel -y >/dev/null 2>&1
		root_gid_hack $TERMUX_PATH/apt install ~/LKM-kernel.deb -y >/dev/null 2>&1
		rm -f ~/LKM-kernel.deb
		echo "[+] Update successfully, please re-run LKM-kernel."
		exit 0
	else
		whereami=$PWD
		echo "[*] Downloading update files..."
		commit_hash=$(curl -s "https://api.github.com/repos/revWhiteShadow/light_kernel_manager/git/refs/tags/${latest_release}" | jq -r '.object.sha')
		git clone https://github.com/revWhiteShadow/light_kernel_manager.git ~/.LKM-kernel
		cd ~/.LKM-kernel
		git reset --hard $commit_hash
		echo "[*] Installing update..."
		root_gid_hack $TERMUX_PATH/make uninstall >/dev/null 2>&1
		root_gid_hack $TERMUX_PATH/make install >/dev/null 2>&1
		cd $whereami
		rm -rf ~/.LKM-kernel
		echo "[+] Update successfully, please re-run LKM-kernel."
		exit 0
	fi
}

main_menu() {
	while true; do
		clear
		echo -e "\e[30;48;2;254;228;208m Light Kernel Manager ${VERSION}$(printf '%*s' $((LINE - 30)) '')\033[0m"
		echo -e "\e[38;2;254;228;208m"
echo -e " _     _  ____  __     [] DEVICE: $(getprop 'ro.product.system.model')"
echo -e " | |   | |/ /  \/  |   [] MANUFACTURER: ${VENDOR}"
echo -e " | |   | ' /| |\/| |   [] CPU: ${chipset}"
echo -e " | |___| . \| |  | |   [] GPU: ${gpu}" | cut -c 1-${LINE}
echo -e " |_____|_|\_\_|  |_|   [] KERNEL VERSION: $(uname -r)" | cut -c 1-${LINE}
echo -e " __________________    [] UPTIME: $(uptime -p)"             
echo -e "__________________     [] ANDROID VERSION: ${ANDROID}"
echo -e "__________________     [] SELINUX: $(getenforce)"
echo -e "__________________     [] ENTROPY: ${ENTROPY}"


		echo -e "\n//////////////"
		echo -e "$(printf '─%.0s' $(seq 1 $LINE))\n"
		echo -e "[] Main Menu\033[0m"

		# Hide cursor
		tput civis

		case $(fzy_select "CPU control\nGPU control\nDRAM control\nMemory settings\nScheduler settings\nNetworking settings\nMiscellaneous settings\nCharging controller\nDisplay color calibration\nLKM Settings\nShow License\nCheck for update\nDonate me\nJoin my telegram channel\nExit" "") in
		"CPU control") cpu_menu ;;
		"GPU control") gpu_menu ;;
		"DRAM control") dram_menu ;;
		"Memory settings") memory_menu ;;
		"Scheduler settings") sched_menu ;;
		"Networking settings") net_menu ;;
		"Miscellaneous settings") misc_menu ;;
		"Charging controller") batt_menu ;;
		"Display color calibration") disp_menu ;;
		"LKM Settings") settings_menu ;;
		"Show License") show_license ;;
		"Check for update") check4update ;;
		"Join my telegram channel") nohup /system/bin/am start -a android.intent.action.VIEW -d https://t.me/godTspeed </dev/null >/dev/null 2>&1 & ;;
		"Donate me") donate ;;
		"Exit") clear && exit 0 ;;
		esac
	done
}

main_menu
